import org.gradle.api.file.Directory
import org.gradle.api.provider.Provider
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFrameworkConfig

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.skie)
    alias(libs.plugins.detekt)
    alias(libs.plugins.binary.compatibility.validator)
    alias(libs.plugins.maven.publish)
}

val libraryVersion: String = providers.gradleProperty("VERSION_NAME").get()
val webContractVersion: String = providers.gradleProperty("CONTRACT_VERSION").get()

// Both versions reach Kotlin through generation, never through a hand-typed
// literal. A literal and its assertion drift together silently — the exact
// defect that let the web contract generator claim 2.0.0 after 2.0.1 shipped,
// with a green test agreeing with it.
val generateKitVersion: TaskProvider<Task> = tasks.register("generateKitVersion") {
    val outputDirectory: Provider<Directory> = layout.buildDirectory.dir("generated/kitVersion/kotlin")
    val version: String = libraryVersion
    val contractVersion: String = webContractVersion

    inputs.property("version", version)
    inputs.property("contractVersion", contractVersion)
    outputs.dir(outputDirectory)

    doLast {
        val packageDirectory: java.io.File = outputDirectory.get().asFile.resolve("tv/nomercy/player/core")
        packageDirectory.mkdirs()
        packageDirectory.resolve("KitVersion.kt").writeText(
            """
            // -----------------------------------------------------------------------------
            //  Copyright (c) NoMercy Entertainment
            //
            //  Licensed under the Apache License, Version 2.0. See LICENSE for details.
            //
            //  SPDX-License-Identifier: Apache-2.0
            // -----------------------------------------------------------------------------

            package tv.nomercy.player.core

            /**
             * This library's own published version. Plugins gate on it through
             * `minCoreVersion`, exactly as `KIT_VERSION` does on the web trio.
             *
             * Generated by the `generateKitVersion` Gradle task from VERSION_NAME in
             * gradle.properties. Do not edit: every write is overwritten next build.
             */
            public const val KIT_VERSION: String = "$version"

            /**
             * The published web trio release whose contract this library implements.
             * Conformance checks read it to pick the contract they measure against.
             *
             * Generated from CONTRACT_VERSION in gradle.properties.
             */
            public const val CONTRACT_VERSION: String = "$contractVersion"

            """.trimIndent(),
        )
    }
}

kotlin {
    explicitApi()
    applyDefaultHierarchyTemplate()

    androidLibrary {
        namespace = "tv.nomercy.player.core"
        compileSdk = 36
        minSdk = 29

        // Android host tests exist from day one so the first `actual` written for
        // Android has somewhere to be tested. Device tests come with the first
        // thing that genuinely needs a device.
        withHostTestBuilder {}.configure {}

        // The engine gate runs on a device, because an ExoPlayer that
        // decodes on a JVM stub proves nothing about the one shipping.
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }.configure {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }

        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions { jvmTarget.set(JvmTarget.JVM_21) }
            }
        }
    }

    jvm {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions { jvmTarget.set(JvmTarget.JVM_21) }
            }
        }
    }

    // One xcframework for both Apple platforms, matching how nomercy-app-kmp's
    // `shared` module already ships to the Tuist project.
    val playerCoreXcf: XCFrameworkConfig = XCFramework("NoMercyPlayerCore")
    listOf(
        iosArm64(),
        iosSimulatorArm64(),
        iosX64(),
        tvosArm64(),
        tvosSimulatorArm64(),
    ).forEach { target ->
        target.binaries.framework {
            baseName = "NoMercyPlayerCore"
            isStatic = true
            // Without this the linker warns and falls back to the bundle name,
            // which collides with any other framework that also went unnamed.
            binaryOption("bundleId", "tv.nomercy.player.core")
            playerCoreXcf.add(this)
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateKitVersion)
            dependencies {
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                // A backend's callbacks arrive on whatever thread the engine
                // uses — VLCJ's native thread, AVPlayer's main queue — and
                // kotlin.synchronized does not exist in commonMain.
                implementation(libs.kotlinx.atomicfu)
            }
        }
        // androidx.startup captures the application Context at process start so
        // it never has to appear in a common signature.
        androidMain.dependencies {
            implementation(libs.androidx.startup)
            // The Android engine. Media3 is what every Android client
            // already uses, and reimplementing its buffering would be
            // worse than anything gained.
            implementation(libs.androidx.media3.exoplayer)
            implementation(libs.androidx.media3.common)
            // The system transport. One Media3 session owns the lock screen,
            // the notification and whatever a car is showing, and it is built
            // here rather than in an app so there is exactly one of it.
            implementation(libs.androidx.media3.session)
            // The data source Media3 reads manifests through, so the sanitizer
            // can sit in front of it. Media3's default source has no place to
            // put an interceptor.
            implementation(libs.androidx.media3.datasource.okhttp)
            implementation(libs.okhttp)
            implementation(libs.kotlinx.coroutines.android)
        }
        // The desktop engine. libVLC decodes practically everything, which is
        // what a desktop client needs when the file came off a disc rip.
        jvmMain.dependencies {
            implementation(libs.vlcj)
        }
        getByName("androidHostTest").dependencies {
            // A real HTTP exchange for the interceptor, because the plumbing it
            // adds over the rule is exactly what a fake transport cannot check.
            implementation(libs.okhttp.mockwebserver)
        }
        getByName("androidDeviceTest").dependencies {
            implementation(libs.androidx.test.runner)
            implementation(libs.androidx.test.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmTest.dependencies {
            // Test-only, deliberately. The method-surface gate asks the player
            // class what it exposes, and a reflection library in the shipped
            // artifact would be a megabyte every consumer carries so that a
            // build-time question could be answered.
            implementation(kotlin("reflect"))
        }
    }
}

skie {
    // SKIE uploads build analytics to Touchlab by default. Off: nothing about
    // this build leaves the machine that ran it.
    analytics {
        enabled.set(false)
    }
}

// The advisory pack runs against this library too. It is guidance for a
// consumer and a hard failure for us: we are the ones writing the examples
// everybody else reads.
dependencies {
    detektPlugins(project(":detekt-player"))
}

detekt {
    // Hand-written sources only. Generated code is not something a human can fix.
    source.setFrom(
        "src/commonMain/kotlin",
        "src/commonTest/kotlin",
        "src/androidMain/kotlin",
        "src/appleMain/kotlin",
        "src/iosMain/kotlin",
        "src/tvosMain/kotlin",
        "src/jvmTest/kotlin",
        "src/jvmMain/kotlin",
    )
    config.setFrom("config/detekt/detekt.yml")
    buildUponDefaultConfig = true
    // No baseline file, deliberately. A baseline is a list of violations that
    // are allowed to stay, and this repo has no history to grandfather in.
}

// The GO/NO-GO gate, on its own so it can be read as a verdict.
//
// These tests already run inside jvmTest, so a red gate blocks `build` whether
// or not this task exists. What it adds is time and a name: it answers "has the
// native port drifted from the ecosystem contract" in seconds, before the
// multiplatform build spends ten minutes arriving at the same answer under a
// heading that says nothing.
tasks.register<Test>("skeletonConformance") {
    group = "verification"
    description = "Checks the port against the vendored contract: events, error codes and behaviour."

    val jvmTest: Test = tasks.named<Test>("jvmTest").get()
    testClassesDirs = jvmTest.testClassesDirs
    classpath = jvmTest.classpath

    filter {
        includeTestsMatching("tv.nomercy.player.core.conformance.*")
        includeTestsMatching("tv.nomercy.player.core.events.CoreEventsRegistryTest")
    }

    testLogging {
        events("failed")
        showStandardStreams = false
    }
}

@OptIn(kotlinx.validation.ExperimentalBCVApi::class)
apiValidation {
    // The rule pack is a build-tool jar detekt loads through a service file, not
    // something application code links against. Its real contract is the ruleset
    // id and the six rule ids, and PlayerRulesTest asserts those exactly. A dump
    // of its class signatures would churn on every rule without guarding anyone.
    ignoredProjects.add("detekt-player")

    // On covers Apple. Kotlin/Native compiles klibs on any host — only linking a
    // framework needs macOS — so the iOS and tvOS public surface is checked on
    // Windows and Linux too, not just on the Mac runner.
    klib {
        enabled = true
        strictValidation = true
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
}
