import org.gradle.api.file.Directory
import org.gradle.api.provider.Provider
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFrameworkConfig

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.skie)
    alias(libs.plugins.detekt)
    alias(libs.plugins.binary.compatibility.validator)
    alias(libs.plugins.maven.publish)
}

val libraryVersion: String = providers.gradleProperty("VERSION_NAME").get()
val webContractVersion: String = providers.gradleProperty("CONTRACT_VERSION").get()

// Both versions reach Kotlin through generation, never through a hand-typed
// literal. A literal and its assertion drift together silently — the exact
// defect that let the web contract generator claim 2.0.0 after 2.0.1 shipped,
// with a green test agreeing with it.
val generateKitVersion: TaskProvider<Task> = tasks.register("generateKitVersion") {
    val outputDirectory: Provider<Directory> = layout.buildDirectory.dir("generated/kitVersion/kotlin")
    val version: String = libraryVersion
    val contractVersion: String = webContractVersion

    inputs.property("version", version)
    inputs.property("contractVersion", contractVersion)
    outputs.dir(outputDirectory)

    doLast {
        val packageDirectory: java.io.File = outputDirectory.get().asFile.resolve("tv/nomercy/player/core")
        packageDirectory.mkdirs()
        packageDirectory.resolve("KitVersion.kt").writeText(
            """
            package tv.nomercy.player.core

            /**
             * This library's own published version. Plugins gate on it through
             * `minCoreVersion`, exactly as `KIT_VERSION` does on the web trio.
             *
             * Generated by the `generateKitVersion` Gradle task from VERSION_NAME in
             * gradle.properties. Do not edit: every write is overwritten next build.
             */
            public const val KIT_VERSION: String = "$version"

            /**
             * The published web trio release whose contract this library implements.
             * Conformance checks read it to pick the contract they measure against.
             *
             * Generated from CONTRACT_VERSION in gradle.properties.
             */
            public const val CONTRACT_VERSION: String = "$contractVersion"

            """.trimIndent(),
        )
    }
}

kotlin {
    explicitApi()
    applyDefaultHierarchyTemplate()

    androidLibrary {
        namespace = "tv.nomercy.player.core"
        compileSdk = 36
        minSdk = 29

        // Android host tests exist from day one so the first `actual` written for
        // Android has somewhere to be tested. Device tests come with the first
        // thing that genuinely needs a device.
        withHostTestBuilder {}.configure {}

        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions { jvmTarget.set(JvmTarget.JVM_21) }
            }
        }
    }

    jvm {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions { jvmTarget.set(JvmTarget.JVM_21) }
            }
        }
    }

    // One xcframework for both Apple platforms, matching how nomercy-app-kmp's
    // `shared` module already ships to the Tuist project.
    val playerCoreXcf: XCFrameworkConfig = XCFramework("NoMercyPlayerCore")
    listOf(
        iosArm64(),
        iosSimulatorArm64(),
        iosX64(),
        tvosArm64(),
        tvosSimulatorArm64(),
    ).forEach { target ->
        target.binaries.framework {
            baseName = "NoMercyPlayerCore"
            isStatic = true
            // Without this the linker warns and falls back to the bundle name,
            // which collides with any other framework that also went unnamed.
            binaryOption("bundleId", "tv.nomercy.player.core")
            playerCoreXcf.add(this)
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateKitVersion)
            dependencies {
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

skie {
    // SKIE uploads build analytics to Touchlab by default. Off: nothing about
    // this build leaves the machine that ran it.
    analytics {
        enabled.set(false)
    }
}

detekt {
    // Hand-written sources only. Generated code is not something a human can fix.
    source.setFrom(
        "src/commonMain/kotlin",
        "src/commonTest/kotlin",
        "src/androidMain/kotlin",
        "src/appleMain/kotlin",
        "src/jvmMain/kotlin",
    )
    config.setFrom("config/detekt/detekt.yml")
    buildUponDefaultConfig = true
    // No baseline file, deliberately. A baseline is a list of violations that
    // are allowed to stay, and this repo has no history to grandfather in.
}

@OptIn(kotlinx.validation.ExperimentalBCVApi::class)
apiValidation {
    // On covers Apple. Kotlin/Native compiles klibs on any host — only linking a
    // framework needs macOS — so the iOS and tvOS public surface is checked on
    // Windows and Linux too, not just on the Mac runner.
    klib {
        enabled = true
        strictValidation = true
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
}
