// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

package tv.nomercy.player.core.media

// One language, however the file spelled it.
//
// A container track says "ger" and the subtitle file beside it says "de", and
// they are the same language: ISO 639-2 has a bibliographic form and a
// terminological form for the same tongue, and a muxer picks whichever its
// author preferred. Comparing the raw strings makes them two languages, so the
// track menu grows a German row and a second German row, and the sidecar never
// replaces the track it duplicates.
//
// Both forms map to the 639-1 code, which is why there are more keys here than
// languages: "ger" and "deu" both arrive at "de".
//
// Generated from the reference's own LANG_CANONICAL rather than typed out. A
// table this size transcribed by hand is a table with a wrong row in it, and a
// wrong row is one language that silently never matches.
internal val LANG_CANONICAL: Map<String, String> = mapOf(
    "aar" to "aa",
    "abk" to "ab",
    "afr" to "af",
    "aka" to "ak",
    "alb" to "sq",
    "sqi" to "sq",
    "amh" to "am",
    "ara" to "ar",
    "arg" to "an",
    "arm" to "hy",
    "hye" to "hy",
    "asm" to "as",
    "ava" to "av",
    "ave" to "ae",
    "aym" to "ay",
    "aze" to "az",
    "bak" to "ba",
    "bam" to "bm",
    "baq" to "eu",
    "eus" to "eu",
    "bel" to "be",
    "ben" to "bn",
    "bih" to "bh",
    "bis" to "bi",
    "bod" to "bo",
    "tib" to "bo",
    "bos" to "bs",
    "bre" to "br",
    "bul" to "bg",
    "bur" to "my",
    "mya" to "my",
    "cat" to "ca",
    "ces" to "cs",
    "cze" to "cs",
    "cha" to "ch",
    "che" to "ce",
    "chu" to "cu",
    "chv" to "cv",
    "cor" to "kw",
    "cos" to "co",
    "cre" to "cr",
    "cym" to "cy",
    "wel" to "cy",
    "dan" to "da",
    "deu" to "de",
    "ger" to "de",
    "div" to "dv",
    "dzo" to "dz",
    "ell" to "el",
    "gre" to "el",
    "eng" to "en",
    "epo" to "eo",
    "est" to "et",
    "fao" to "fo",
    "fas" to "fa",
    "per" to "fa",
    "fij" to "fj",
    "fin" to "fi",
    "fra" to "fr",
    "fre" to "fr",
    "fry" to "fy",
    "ful" to "ff",
    "gla" to "gd",
    "gle" to "ga",
    "glg" to "gl",
    "glv" to "gv",
    "grn" to "gn",
    "guj" to "gu",
    "hat" to "ht",
    "hau" to "ha",
    "heb" to "he",
    "her" to "hz",
    "hin" to "hi",
    "hmo" to "ho",
    "hrv" to "hr",
    "hun" to "hu",
    "ibo" to "ig",
    "ido" to "io",
    "iii" to "ii",
    "iku" to "iu",
    "ile" to "ie",
    "ina" to "ia",
    "ind" to "id",
    "ipk" to "ik",
    "isl" to "is",
    "ice" to "is",
    "ita" to "it",
    "jav" to "jv",
    "jpn" to "ja",
    "kal" to "kl",
    "kan" to "kn",
    "kas" to "ks",
    "kat" to "ka",
    "geo" to "ka",
    "kau" to "kr",
    "kaz" to "kk",
    "khm" to "km",
    "kik" to "ki",
    "kin" to "rw",
    "kir" to "ky",
    "kom" to "kv",
    "kon" to "kg",
    "kor" to "ko",
    "kua" to "kj",
    "kur" to "ku",
    "lao" to "lo",
    "lat" to "la",
    "lav" to "lv",
    "lim" to "li",
    "lin" to "ln",
    "lit" to "lt",
    "ltz" to "lb",
    "lub" to "lu",
    "lug" to "lg",
    "mac" to "mk",
    "mkd" to "mk",
    "mal" to "ml",
    "mao" to "mi",
    "mri" to "mi",
    "mar" to "mr",
    "mah" to "mh",
    "may" to "ms",
    "msa" to "ms",
    "mlg" to "mg",
    "mlt" to "mt",
    "mon" to "mn",
    "nau" to "na",
    "nav" to "nv",
    "nbl" to "nr",
    "nde" to "nd",
    "ndo" to "ng",
    "nep" to "ne",
    "nld" to "nl",
    "dut" to "nl",
    "nno" to "nn",
    "nob" to "nb",
    "nor" to "no",
    "nya" to "ny",
    "oci" to "oc",
    "oji" to "oj",
    "ori" to "or",
    "orm" to "om",
    "oss" to "os",
    "pan" to "pa",
    "pli" to "pi",
    "pol" to "pl",
    "por" to "pt",
    "pus" to "ps",
    "que" to "qu",
    "roh" to "rm",
    "ron" to "ro",
    "rum" to "ro",
    "run" to "rn",
    "rus" to "ru",
    "sag" to "sg",
    "san" to "sa",
    "sin" to "si",
    "slk" to "sk",
    "slo" to "sk",
    "slv" to "sl",
    "sme" to "se",
    "smo" to "sm",
    "sna" to "sn",
    "snd" to "sd",
    "som" to "so",
    "sot" to "st",
    "spa" to "es",
    "srd" to "sc",
    "srp" to "sr",
    "ssw" to "ss",
    "sun" to "su",
    "swa" to "sw",
    "swe" to "sv",
    "tah" to "ty",
    "tam" to "ta",
    "tat" to "tt",
    "tel" to "te",
    "tgk" to "tg",
    "tgl" to "tl",
    "tha" to "th",
    "tir" to "ti",
    "ton" to "to",
    "tsn" to "tn",
    "tso" to "ts",
    "tuk" to "tk",
    "tur" to "tr",
    "twi" to "tw",
    "uig" to "ug",
    "ukr" to "uk",
    "urd" to "ur",
    "uzb" to "uz",
    "ven" to "ve",
    "vie" to "vi",
    "vol" to "vo",
    "wln" to "wa",
    "wol" to "wo",
    "xho" to "xh",
    "yid" to "yi",
    "yor" to "yo",
    "zha" to "za",
    "zho" to "zh",
    "chi" to "zh",
    "zul" to "zu",
)

// The 639-1 two-letter form, for comparison rather than for display.
//
// A BCP-47 tag keeps only its primary subtag, so "de-AT" and "de" compare equal:
// a viewer choosing German does not mean to exclude Austrian German. Null and
// blank come back untouched, because "unknown language" is a real answer and
// inventing one for it would make two unlabelled tracks look like the same one.
public fun normalizeLanguage(lang: String?): String? {
    if (lang.isNullOrEmpty()) return lang

    val primary: String = lang.substringBefore('-').lowercase()
    return LANG_CANONICAL[primary] ?: primary
}
