// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

package tv.nomercy.player.core.events


import tv.nomercy.player.core.media.PlaylistItem
import tv.nomercy.player.core.player.ActionOptions

// The typed key registry — Kotlin's answer to the web BaseEventMap. Every
// name string is the web key verbatim, because that string is the shared
// identity across the web trio, this library, the docs and the wire. The
// payload type rides on the key, so on(CoreEvents.Time) hands the listener
// a TimeUpdate with no cast and no event-map generic.
//
// Generated by scripts/generate-event-registry.py. A hand-maintained
// registry of 152 keys drifts, and a key that quietly disappears takes its
// listeners with it. Keys that already existed keep their property names
// and payload types, so regenerating never breaks a call site.
//
// Only v2 names appear. The v1 aliases (current, finished, qualityLevels)
// are never registered — they are a compatibility layer the web trio owns.
@Suppress("TooManyFunctions", "LargeClass")
public object CoreEvents {
    public val Activity: EventKey<ActivityPayload> = EventKey("activity")
    public val AudioTrack: EventKey<AudioTrackPayload> = EventKey("audioTrack")
    public val AudioTrackPrevented: EventKey<AudioTrackPreventedPayload> = EventKey("audioTrackPrevented")
    public val AudioTrackState: EventKey<AudioTrackStatePayload> = EventKey("audioTrackState")
    public val AuthFailed: EventKey<AuthFailedPayload> = EventKey("auth:failed")
    public val AuthRefreshed: EventKey<AuthRefreshedPayload> = EventKey("auth:refreshed")
    public val AuthReady: EventKey<Unit> = EventKey("authReady")
    public val AuthReadyError: EventKey<PlayerErrorEvent> = EventKey("authReadyError")
    public val BackendChanged: EventKey<BackendChangedPayload> = EventKey("backend:changed")
    public val BackendError: EventKey<BackendErrorPayload> = EventKey("backend:error")
    public val BackendLoaded: EventKey<BackendLoadedPayload> = EventKey("backend:loaded")
    public val BackendLoading: EventKey<BackendLoadingPayload> = EventKey("backend:loading")
    public val BackendRateChange: EventKey<RateChange> = EventKey("backend:ratechange")
    public val BackendStalled: EventKey<BackendStalledPayload> = EventKey("backend:stalled")
    public val BackendWaiting: EventKey<Unit> = EventKey("backend:waiting")
    public val Backlog: EventKey<QueueChange> = EventKey("backlog")
    public val BacklogAppend: EventKey<tv.nomercy.player.core.events.QueueAppend> = EventKey("backlog:append")
    public val BacklogClear: EventKey<tv.nomercy.player.core.events.QueueClear> = EventKey("backlog:clear")
    public val BacklogRemove: EventKey<tv.nomercy.player.core.events.QueueRemove> = EventKey("backlog:remove")
    public val BeforeAudioTrack: EventKey<BeforeEvent<BeforeAudioTrackPayload>> = EventKey("beforeAudioTrack")
    public val BeforeDispose: EventKey<BeforeEvent<Unit>> = EventKey("beforeDispose")
    public val BeforeLanguage: EventKey<BeforeEvent<BeforeLanguagePayload>> = EventKey("beforeLanguage")
    public val BeforeLoad: EventKey<BeforeEvent<BeforeLoadPayload>> = EventKey("beforeLoad")
    public val BeforeMutation: EventKey<BeforeEvent<BeforeMutationPayload>> = EventKey("beforeMutation")
    public val BeforeMute: EventKey<BeforeEvent<MuteChange>> = EventKey("beforeMute")
    public val BeforeNext: EventKey<BeforeEvent<ActionOptions>> = EventKey("beforeNext")
    public val BeforePause: EventKey<BeforeEvent<ActionOptions>> = EventKey("beforePause")
    public val BeforePlay: EventKey<BeforeEvent<ActionOptions>> = EventKey("beforePlay")
    public val BeforePlaybackRate: EventKey<BeforeEvent<RateChange>> = EventKey("beforePlaybackRate")
    public val BeforePrevious: EventKey<BeforeEvent<ActionOptions>> = EventKey("beforePrevious")
    public val BeforeRepeat: EventKey<BeforeEvent<RepeatChange>> = EventKey("beforeRepeat")
    public val BeforeSeek: EventKey<BeforeEvent<SeekPosition>> = EventKey("beforeSeek")
    public val BeforeSetup: EventKey<BeforeEvent<Unit>> = EventKey("beforeSetup")
    public val BeforeShuffle: EventKey<BeforeEvent<ShuffleChange>> = EventKey("beforeShuffle")
    public val BeforeStop: EventKey<BeforeEvent<ActionOptions>> = EventKey("beforeStop")
    public val BeforeSubtitle: EventKey<BeforeEvent<BeforeSubtitlePayload>> = EventKey("beforeSubtitle")
    public val BeforeTransfer: EventKey<BeforeEvent<BeforeTransferPayload>> = EventKey("beforeTransfer")
    public val BeforeVolume: EventKey<BeforeEvent<VolumeChange>> = EventKey("beforeVolume")
    public val CastState: EventKey<CastStatePayload> = EventKey("castState")
    public val Chapter: EventKey<ChapterPayload> = EventKey("chapter")
    public val Chapters: EventKey<ChaptersPayload> = EventKey("chapters")
    public val ConfigResolved: EventKey<ConfigResolvedPayload> = EventKey("configResolved")
    public val ConfigResolvedError: EventKey<PlayerErrorEvent> = EventKey("configResolvedError")
    public val CueEnter: EventKey<CueEvent> = EventKey("cue:enter")
    public val CueExit: EventKey<CueEvent> = EventKey("cue:exit")
    public val Dispose: EventKey<Unit> = EventKey("dispose")
    public val DisposePrevented: EventKey<PreventedAction> = EventKey("disposePrevented")
    public val Duration: EventKey<Double> = EventKey("duration")
    public val Ended: EventKey<Unit> = EventKey("ended")
    public val Error: EventKey<PlayerErrorEvent> = EventKey("error")
    public val Fatal: EventKey<PlayerErrorEvent> = EventKey("fatal")
    public val FetchComplete: EventKey<FetchCompletePayload> = EventKey("fetch:complete")
    public val FetchRetry: EventKey<FetchRetryPayload> = EventKey("fetch:retry")
    public val FetchStart: EventKey<FetchStartPayload> = EventKey("fetch:start")
    public val FirstFrame: EventKey<Unit> = EventKey("firstFrame")
    public val Info: EventKey<PlayerErrorEvent> = EventKey("info")
    public val Item: EventKey<ItemChange> = EventKey("item")
    public val ItemEndingSoon: EventKey<tv.nomercy.player.core.events.ItemEndingSoon> = EventKey("itemEndingSoon")
    public val Language: EventKey<LanguagePayload> = EventKey("language")
    public val LanguagePrevented: EventKey<LanguagePreventedPayload> = EventKey("languagePrevented")
    public val LevelSwitched: EventKey<LevelSwitchedPayload> = EventKey("level-switched")
    public val ListenersChanged: EventKey<ListenersChangedPayload> = EventKey("listeners-changed")
    public val LoadPrevented: EventKey<LoadPreventedPayload> = EventKey("loadPrevented")
    public val MediaReady: EventKey<Unit> = EventKey("mediaReady")
    public val MediaReadyError: EventKey<PlayerErrorEvent> = EventKey("mediaReadyError")
    public val MutationPrevented: EventKey<MutationPreventedPayload> = EventKey("mutationPrevented")
    public val Mute: EventKey<MuteChange> = EventKey("mute")
    public val MutePrevented: EventKey<PreventedAction> = EventKey("mutePrevented")
    public val NetworkOffline: EventKey<Unit> = EventKey("network:offline")
    public val NetworkOnline: EventKey<Unit> = EventKey("network:online")
    public val NetworkSlow: EventKey<NetworkSlowPayload> = EventKey("network:slow")
    public val Next: EventKey<PlaySource> = EventKey("next")
    public val NextPrevented: EventKey<PreventedAction> = EventKey("nextPrevented")
    public val Pause: EventKey<PlaySource> = EventKey("pause")
    public val PausePrevented: EventKey<PreventedAction> = EventKey("pausePrevented")
    public val Phase: EventKey<PhaseChange> = EventKey("phase")
    public val Play: EventKey<PlaySource> = EventKey("play")
    public val PlayPrevented: EventKey<PreventedAction> = EventKey("playPrevented")
    public val PlaybackMetrics: EventKey<PlaybackMetrics> = EventKey("playback:metrics")
    public val PlaybackRate: EventKey<RateChange> = EventKey("playbackRate")
    public val PlaybackRatePrevented: EventKey<PreventedAction> = EventKey("playbackRatePrevented")
    public val Playing: EventKey<Unit> = EventKey("playing")
    public val PlaylistError: EventKey<PlaylistErrorPayload> = EventKey("playlistError")
    public val PlaylistReady: EventKey<PlaylistReadyPayload> = EventKey("playlistReady")
    public val PlaylistResolveError: EventKey<PlayerErrorEvent> = EventKey("playlistResolveError")
    public val PlaylistResolving: EventKey<PlaylistResolvingPayload> = EventKey("playlistResolving")
    public val PluginDisabled: EventKey<PluginDisabledPayload> = EventKey("plugin:disabled")
    public val PluginDisposed: EventKey<PluginDisposedPayload> = EventKey("plugin:disposed")
    public val PluginEnabled: EventKey<PluginEnabledPayload> = EventKey("plugin:enabled")
    public val PluginError: EventKey<PlayerErrorEvent> = EventKey("plugin:error")
    public val PluginFailed: EventKey<PluginFailedPayload> = EventKey("plugin:failed")
    public val PluginInstalled: EventKey<PluginInstalledPayload> = EventKey("plugin:installed")
    public val PluginOptsChanged: EventKey<PluginOptsChangedPayload> = EventKey("plugin:opts:changed")
    public val PluginWarning: EventKey<PlayerErrorEvent> = EventKey("plugin:warning")
    public val PluginsRegistered: EventKey<Unit> = EventKey("pluginsRegistered")
    public val PluginsRegisteredError: EventKey<PlayerErrorEvent> = EventKey("pluginsRegisteredError")
    public val PluginsRegistering: EventKey<Unit> = EventKey("pluginsRegistering")
    public val PluginsRegisteringError: EventKey<PlayerErrorEvent> = EventKey("pluginsRegisteringError")
    public val PreloadComplete: EventKey<PreloadCompletePayload> = EventKey("preloadComplete")
    public val PreloadError: EventKey<PreloadErrorPayload> = EventKey("preloadError")
    public val PreloadProgress: EventKey<PreloadProgressPayload> = EventKey("preloadProgress")
    public val PreloadStart: EventKey<PreloadStartPayload> = EventKey("preloadStart")
    public val Previous: EventKey<PlaySource> = EventKey("previous")
    public val PreviousPrevented: EventKey<PreventedAction> = EventKey("previousPrevented")
    public val Progress: EventKey<ProgressPayload> = EventKey("progress")
    public val QualityState: EventKey<QualityStatePayload> = EventKey("qualityState")
    public val Queue: EventKey<QueueChange> = EventKey("queue")
    public val QueueAppend: EventKey<tv.nomercy.player.core.events.QueueAppend> = EventKey("queue:append")
    public val QueueClear: EventKey<tv.nomercy.player.core.events.QueueClear> = EventKey("queue:clear")
    public val QueueExhausted: EventKey<Unit> = EventKey("queue:exhausted")
    public val QueueInsert: EventKey<tv.nomercy.player.core.events.QueueInsert> = EventKey("queue:insert")
    public val QueueMove: EventKey<tv.nomercy.player.core.events.QueueMove> = EventKey("queue:move")
    public val QueuePrepend: EventKey<tv.nomercy.player.core.events.QueuePrepend> = EventKey("queue:prepend")
    public val QueueRemove: EventKey<tv.nomercy.player.core.events.QueueRemove> = EventKey("queue:remove")
    public val QueueShuffle: EventKey<QueueChange> = EventKey("queue:shuffle")
    public val QueueSort: EventKey<QueueChange> = EventKey("queue:sort")
    public val Ready: EventKey<Unit> = EventKey("ready")
    public val Repeat: EventKey<RepeatChange> = EventKey("repeat")
    public val RepeatPrevented: EventKey<PreventedAction> = EventKey("repeatPrevented")
    public val Seek: EventKey<SeekPosition> = EventKey("seek")
    public val SeekPrevented: EventKey<PreventedAction> = EventKey("seekPrevented")
    public val Seeked: EventKey<SeekPosition> = EventKey("seeked")
    public val SetupStart: EventKey<SetupStartPayload> = EventKey("setupStart")
    public val SetupStartError: EventKey<PlayerErrorEvent> = EventKey("setupStartError")
    public val Shuffle: EventKey<ShuffleChange> = EventKey("shuffle")
    public val ShufflePrevented: EventKey<PreventedAction> = EventKey("shufflePrevented")
    public val Stop: EventKey<PlaySource> = EventKey("stop")
    public val StopPrevented: EventKey<PreventedAction> = EventKey("stopPrevented")
    public val StreamEncrypted: EventKey<StreamEncryptedPayload> = EventKey("stream:encrypted")
    public val StreamError: EventKey<StreamError> = EventKey("stream:error")
    public val StreamFragmentLoaded: EventKey<StreamFragmentLoadedPayload> = EventKey("stream:fragment-loaded")
    public val StreamLevelConsidered: EventKey<StreamLevelConsideredPayload> = EventKey("stream:level-considered")
    public val StreamLevelSwitched: EventKey<StreamLevelSwitchedPayload> = EventKey("stream:level-switched")
    public val StreamManifestLoaded: EventKey<StreamManifestLoadedPayload> = EventKey("stream:manifest-loaded")
    public val StreamsReady: EventKey<Unit> = EventKey("streamsReady")
    public val StreamsReadyError: EventKey<PlayerErrorEvent> = EventKey("streamsReadyError")
    public val Subtitle: EventKey<SubtitlePayload> = EventKey("subtitle")
    public val SubtitleCue: EventKey<SubtitleCueChange> = EventKey("subtitleCue")
    public val SubtitlePrevented: EventKey<SubtitlePreventedPayload> = EventKey("subtitlePrevented")
    public val SubtitleStyle: EventKey<SubtitleStyle> = EventKey("subtitleStyle")
    public val Subtitles: EventKey<SubtitlesPayload> = EventKey("subtitles")
    public val Time: EventKey<TimeUpdate> = EventKey("time")
    public val TransferPrevented: EventKey<TransferPreventedPayload> = EventKey("transferPrevented")
    public val TransitionCancelled: EventKey<TransitionCancelledPayload> = EventKey("transitionCancelled")
    public val TransitionComplete: EventKey<TransitionCompletePayload> = EventKey("transitionComplete")
    public val TransitionProgress: EventKey<TransitionProgressPayload> = EventKey("transitionProgress")
    public val TransitionStart: EventKey<TransitionStartPayload> = EventKey("transitionStart")
    public val VisibilityHidden: EventKey<Unit> = EventKey("visibility:hidden")
    public val VisibilityVisible: EventKey<Unit> = EventKey("visibility:visible")
    public val Volume: EventKey<VolumeChange> = EventKey("volume")
    public val VolumePrevented: EventKey<PreventedAction> = EventKey("volumePrevented")
    public val Warning: EventKey<PlayerErrorEvent> = EventKey("warning")

    // Every key, for the conformance gate that checks this registry against
    // the contract it was generated from.
    public val all: List<EventKey<*>> = listOf(
        Activity,
        AudioTrack,
        AudioTrackPrevented,
        AudioTrackState,
        AuthFailed,
        AuthRefreshed,
        AuthReady,
        AuthReadyError,
        BackendChanged,
        BackendError,
        BackendLoaded,
        BackendLoading,
        BackendRateChange,
        BackendStalled,
        BackendWaiting,
        Backlog,
        BacklogAppend,
        BacklogClear,
        BacklogRemove,
        BeforeAudioTrack,
        BeforeDispose,
        BeforeLanguage,
        BeforeLoad,
        BeforeMutation,
        BeforeMute,
        BeforeNext,
        BeforePause,
        BeforePlay,
        BeforePlaybackRate,
        BeforePrevious,
        BeforeRepeat,
        BeforeSeek,
        BeforeSetup,
        BeforeShuffle,
        BeforeStop,
        BeforeSubtitle,
        BeforeTransfer,
        BeforeVolume,
        CastState,
        Chapter,
        Chapters,
        ConfigResolved,
        ConfigResolvedError,
        CueEnter,
        CueExit,
        Dispose,
        DisposePrevented,
        Duration,
        Ended,
        Error,
        Fatal,
        FetchComplete,
        FetchRetry,
        FetchStart,
        FirstFrame,
        Info,
        Item,
        ItemEndingSoon,
        Language,
        LanguagePrevented,
        LevelSwitched,
        ListenersChanged,
        LoadPrevented,
        MediaReady,
        MediaReadyError,
        MutationPrevented,
        Mute,
        MutePrevented,
        NetworkOffline,
        NetworkOnline,
        NetworkSlow,
        Next,
        NextPrevented,
        Pause,
        PausePrevented,
        Phase,
        Play,
        PlayPrevented,
        PlaybackMetrics,
        PlaybackRate,
        PlaybackRatePrevented,
        Playing,
        PlaylistError,
        PlaylistReady,
        PlaylistResolveError,
        PlaylistResolving,
        PluginDisabled,
        PluginDisposed,
        PluginEnabled,
        PluginError,
        PluginFailed,
        PluginInstalled,
        PluginOptsChanged,
        PluginWarning,
        PluginsRegistered,
        PluginsRegisteredError,
        PluginsRegistering,
        PluginsRegisteringError,
        PreloadComplete,
        PreloadError,
        PreloadProgress,
        PreloadStart,
        Previous,
        PreviousPrevented,
        Progress,
        QualityState,
        Queue,
        QueueAppend,
        QueueClear,
        QueueExhausted,
        QueueInsert,
        QueueMove,
        QueuePrepend,
        QueueRemove,
        QueueShuffle,
        QueueSort,
        Ready,
        Repeat,
        RepeatPrevented,
        Seek,
        SeekPrevented,
        Seeked,
        SetupStart,
        SetupStartError,
        Shuffle,
        ShufflePrevented,
        Stop,
        StopPrevented,
        StreamEncrypted,
        StreamError,
        StreamFragmentLoaded,
        StreamLevelConsidered,
        StreamLevelSwitched,
        StreamManifestLoaded,
        StreamsReady,
        StreamsReadyError,
        Subtitle,
        SubtitleCue,
        SubtitlePrevented,
        SubtitleStyle,
        Subtitles,
        Time,
        TransferPrevented,
        TransitionCancelled,
        TransitionComplete,
        TransitionProgress,
        TransitionStart,
        VisibilityHidden,
        VisibilityVisible,
        Volume,
        VolumePrevented,
        Warning,
    )
}
