// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

package tv.nomercy.player.core.events


import tv.nomercy.player.core.media.PlaylistItem
import tv.nomercy.player.core.player.ActionOptions

// Generated by scripts/generate-event-registry.py from the pinned
// contract. One data class per event whose payload the contract states as
// an inline object literal; named payload types are hand-authored and
// mapped through the script's NAMED_TYPES.
//
// Every `number` becomes a Double. The contract's type text cannot say
// which numbers are counts and which are seconds, and guessing from the
// field name would be wrong somewhere quiet.

public data class ActivityPayload(
    val active: Boolean,
)

public data class AudioTrackPayload(
    val id: Double? = null,
)

public data class AudioTrackPreventedPayload(
    val reason: String,
    val cause: Any? = null,
)

public data class AudioTrackStatePayload(
    val state: String,
)

public data class AuthFailedPayload(
    val error: Any? = null,
)

public data class AuthRefreshedPayload(
    val tokenAcquiredAt: Double,
)

public data class BackendChangedPayload(
    val kind: String,
)

public data class BackendErrorPayload(
    val error: Any? = null,
    val kind: String,
)

public data class BackendLoadedPayload(
    val url: String,
    val kind: String,
    val duration: Double,
)

public data class BackendLoadingPayload(
    val url: String,
    val kind: String,
)

public data class BackendStalledPayload(
    val time: Double,
)

public data class BeforeAudioTrackPayload(
    val id: Double,
)

public data class BeforeLanguagePayload(
    val lang: String,
)

public data class BeforeLoadPayload(
    val item: PlaylistItem,
    val source: String? = null,
)

public data class BeforeMutationPayload(
    val method: String,
    val args: List<Any?>,
    val phase: tv.nomercy.player.core.player.PlayerPhase,
    val dispatchStack: List<String>,
)

public data class BeforeSubtitlePayload(
    val track: Double? = null,
)

public data class BeforeTransferPayload(
    val target: CastTarget,
)

public data class CastStatePayload(
    val state: Any? = null,
)

public data class ChapterPayload(
    val index: Double,
    val title: String,
)

public data class ChaptersPayload(
    val chapters: List<Any?>,
)

public data class ConfigResolvedPayload(
    val config: Any? = null,
)

public data class FetchCompletePayload(
    val url: String,
    val ok: Boolean,
    val status: Double? = null,
    val durationMs: Double,
    val pluginId: String? = null,
)

public data class FetchRetryPayload(
    val url: String,
    val attempt: Double,
    val reason: String,
    val delayMs: Double,
    val pluginId: String? = null,
)

public data class FetchStartPayload(
    val url: String,
    val pluginId: String? = null,
)

public data class LanguagePayload(
    val lang: String,
)

public data class LanguagePreventedPayload(
    val reason: String,
    val cause: Any? = null,
)

public data class LevelSwitchedPayload(
    val level: Double,
)

public data class ListenersChangedPayload(
    val name: String,
    val count: Double,
)

public data class LoadPreventedPayload(
    val reason: String,
    val cause: Any? = null,
)

public data class MutationPreventedPayload(
    val method: String,
    val reason: String,
    val cause: Any? = null,
)

public data class NetworkSlowPayload(
    val rttMs: String,
)

public data class PlaylistErrorPayload(
    val url: String,
    val error: Any? = null,
    val code: String,
)

public data class PlaylistReadyPayload(
    val length: Double,
)

public data class PlaylistResolvingPayload(
    val url: String,
)

public data class PluginDisabledPayload(
    val id: String,
    val reason: String? = null,
)

public data class PluginDisposedPayload(
    val id: String,
)

public data class PluginEnabledPayload(
    val id: String,
)

public data class PluginFailedPayload(
    val id: String,
    val error: Any? = null,
)

public data class PluginInstalledPayload(
    val id: String,
    val version: String,
)

public data class PluginOptsChangedPayload(
    val id: String,
    val opts: Any? = null,
)

public data class PreloadCompletePayload(
    val item: PlaylistItem,
)

public data class PreloadErrorPayload(
    val item: PlaylistItem,
    val error: Any? = null,
)

public data class PreloadProgressPayload(
    val item: PlaylistItem,
    val loaded: Double,
    val total: Double,
)

public data class PreloadStartPayload(
    val item: PlaylistItem,
    val assets: List<Any?>,
)

public data class ProgressPayload(
    val time: Double,
    val duration: Double,
    val percentage: Double,
)

public data class QualityStatePayload(
    val state: String,
)

public data class SetupStartPayload(
    val container: Any? = null,
)

public data class StreamEncryptedPayload(
    val initData: Any? = null,
    val initDataType: String,
)

public data class StreamFragmentLoadedPayload(
    val url: String,
    val durationMs: Double,
)

public data class StreamLevelConsideredPayload(
    val candidate: Double,
    val decided: Double,
    val reason: String,
)

public data class StreamLevelSwitchedPayload(
    val level: Double,
    val label: String,
)

public data class StreamManifestLoadedPayload(
    val url: String,
)

public data class SubtitlePayload(
    val track: Double? = null,
)

public data class SubtitlePreventedPayload(
    val reason: String,
    val cause: Any? = null,
)

public data class SubtitlesPayload(
    val tracks: List<Any?>,
)

public data class TransferPreventedPayload(
    val reason: String,
    val cause: Any? = null,
)

public data class TransitionCancelledPayload(
    val reason: String,
)

public data class TransitionCompletePayload(
    val from: PlaylistItem,
    val to: PlaylistItem,
)

public data class TransitionProgressPayload(
    val outgoing: PlaylistItem,
    val incoming: PlaylistItem,
    val fraction: Double,
)

public data class TransitionStartPayload(
    val outgoing: PlaylistItem,
    val incoming: PlaylistItem,
)
