// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

package tv.nomercy.player.core.cues

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

// The shape the media server writes for chapters: an identifier line, then the
// timing, then the title.
private val CHAPTERS = """
WEBVTT

Chapter 1
00:00:00.000 --> 00:01:14.833
Scene 01

Chapter 2
00:01:14.833 --> 00:02:17.417
Intro
""".trimIndent()

// And for scrubber previews: one sheet, a rectangle per cue.
private val SPRITES = """
WEBVTT

00:00:00.000 --> 00:00:10.000
thumbs.webp#xywh=0,0,320,178

00:00:10.000 --> 00:00:20.000
thumbs.webp#xywh=320,0,320,178
""".trimIndent()

// A single-cue file, so a test about ONE cue body does not restate the format.
private fun oneCue(body: String): String = "WEBVTT\n\n00:00:00.000 --> 00:00:05.000\n$body"

private const val CRLF = "\r\n"

// One parser for a format three hand-rolled readers each understood slightly
// differently. Chapters, thumbnails and subtitles are all WebVTT, and three
// readers of one format is three chances to disagree about it.
class VttParserTest {

    @Test
    fun anHourlessTimestampIsStillATimestamp() {
        // The hour field is optional in the format and producers leave it off
        // for short items. Demanding it rejects half the files.
        assertEquals(74.833, parseVttTimestamp("00:01:14.833")!!, 1e-6)
        assertEquals(74.833, parseVttTimestamp("01:14.833")!!, 1e-6)
    }

    @Test
    fun aCommaDecimalIsAccepted() {
        // SRT writes the fraction with a comma, and tools that convert between
        // the two leave it behind more often than they should.
        assertEquals(74.833, parseVttTimestamp("00:01:14,833")!!, 1e-6)
    }

    @Test
    fun garbageIsNullRatherThanZero() {
        // Zero is a real timestamp. Returning it for unparseable text puts a cue
        // at the start of the film instead of reporting the file is wrong.
        assertNull(parseVttTimestamp("not-a-time"))
        assertNull(parseVttTimestamp(""))
        assertNull(parseVttTimestamp("00:00:00:000"))
    }

    @Test
    fun chapterCuesCarryTheirTitleAsTheBody() {
        val cues: List<VttCue> = parseVtt(CHAPTERS)

        assertEquals(2, cues.size)
        assertEquals("Scene 01", cues[0].body)
        assertEquals(0.0, cues[0].start)
        assertEquals(74.833, cues[0].end, 1e-6)
    }

    @Test
    fun anIdentifierLineBeforeTheTimingIsNotMistakenForContent() {
        // Chapter files carry one. Assuming the timing is the first line makes
        // every chapter title "Chapter 1".
        assertTrue(parseVtt(CHAPTERS).none { it.body.startsWith("Chapter ") })
    }

    @Test
    fun theHeaderIsNotACue() {
        assertTrue(parseVtt(CHAPTERS).none { it.body.contains("WEBVTT") })
    }

    @Test
    fun cueSettingsOnTheEndTimestampDoNotBreakIt() {
        // Subtitles carry alignment and position on that line. Parsing the whole
        // field fails on every styled cue.
        val cues: List<VttCue> = parseVtt(
            "WEBVTT\n\n00:00:01.000 --> 00:00:04.000 align:start position:10%\nHello",
        )

        assertEquals(1, cues.size)
        assertEquals(4.0, cues[0].end)
    }

    @Test
    fun aNoteBlockIsSkipped() {
        // WebVTT comments are a block with no timing line, and a parser that
        // assumed every block was a cue would emit one with a nonsense time.
        val cues: List<VttCue> = parseVtt(
            "WEBVTT\n\nNOTE this file was generated by a scanner\n\n00:00:01.000 --> 00:00:02.000\nHi",
        )

        assertEquals(1, cues.size)
        assertEquals("Hi", cues[0].body)
    }

    @Test
    fun aMultiLineCueKeepsItsLineBreaks() {
        // Subtitles are wrapped deliberately, and joining the lines with a space
        // rewraps them wherever the renderer decides.
        val cues: List<VttCue> = parseVtt("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nFirst line\nSecond line")

        assertEquals("First line\nSecond line", cues[0].body)
    }

    @Test
    fun aCueWithNoBodyIsNotACue() {
        // A timing with nothing under it renders as a blank subtitle: a black
        // box with no text, which looks like a bug rather than silence.
        assertTrue(parseVtt("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\n").isEmpty())
    }

    @Test
    fun aTruncatedFileYieldsWhatSurvivedRatherThanNothing() {
        // A download cut short. The cues that arrived are still usable, and
        // throwing away the whole file loses subtitles that would have worked.
        val cues: List<VttCue> = parseVtt("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nGood\n\n00:00:03.000 -->")

        assertEquals(1, cues.size)
    }

    @Test
    fun spriteCuesResolveTheirRectangles() {
        val sprites: List<SpriteCue> = parseVttSprite(SPRITES)

        assertEquals(2, sprites.size)
        assertEquals(0, sprites[0].x)
        assertEquals(320, sprites[1].x)
        assertEquals(320, sprites[0].width)
        assertEquals(178, sprites[0].height)
        assertEquals("thumbs.webp", sprites[0].url)
    }

    @Test
    fun aRelativeSheetIsResolvedAgainstTheVttsOwnDirectory() {
        // `baseUrl` is the URL of the VTT FILE, which is what loadSpriteSet hands
        // over. This test used to pass a bare directory, so it agreed with an
        // implementation that appended to whatever it was given — and the real
        // caller passes the file, which resolved every sheet to
        // `.../sprite.vtt/thumbs.webp`. A 404, and no thumbnail could ever paint.
        val sprites: List<SpriteCue> = parseVttSprite(
            SPRITES,
            baseUrl = "https://server.test/media/previews/sprite.vtt",
        )

        assertEquals("https://server.test/media/previews/thumbs.webp", sprites[0].url)
    }

    @Test
    fun aRootRelativeSheetResolvesAgainstTheOriginNotTheDirectory() {
        val sprites: List<SpriteCue> = parseVttSprite(
            SPRITES.replace("thumbs.webp", "/shared/thumbs.webp"),
            baseUrl = "https://server.test/media/previews/sprite.vtt",
        )

        assertEquals("https://server.test/shared/thumbs.webp", sprites[0].url)
    }

    @Test
    fun aCrlfFileIsStillABlockPerCue() {
        // Most encoders emit CRLF. The block separator is two newlines, so a
        // carriage-return pair never matched it: the whole file arrived as ONE
        // block and the first arrow in it produced a single cue whose body was
        // the rest of the document. Subtitles became one cue holding the file.
        val crlf: String = listOf(
            "WEBVTT",
            "",
            "00:00:01.000 --> 00:00:02.000",
            "First",
            "",
            "00:00:03.000 --> 00:00:04.000",
            "Second",
        ).joinToString(CRLF)

        val cues: List<VttCue> = parseVtt(crlf)

        assertEquals(2, cues.size)
        assertEquals("First", cues[0].body)
        assertEquals("Second", cues[1].body)
    }

    @Test
    fun aBodyThatIsNotJustAReferenceIsNotASprite() {
        // Anchored on purpose. Searching for the fragment and splitting what came
        // after it accepted a subtitle that happens to mention a rectangle, and
        // accepted a negative width — a sprite that draws nothing, positioned
        // where nothing else agrees it is.
        val trailing: List<SpriteCue> = parseVttSprite(
            oneCue("thumbs.webp#xywh=0,0,320,178 and more"),
        )
        val negative: List<SpriteCue> = parseVttSprite(
            oneCue("thumbs.webp#xywh=0,0,-320,178"),
        )

        assertEquals(0, trailing.size)
        assertEquals(0, negative.size)
    }

    @Test
    fun anAbsoluteSheetIsLeftAlone() {
        val absolute: String = SPRITES.replace("thumbs.webp", "https://cdn.test/thumbs.webp")

        val sprites: List<SpriteCue> = parseVttSprite(absolute, baseUrl = "https://server.test/media")

        assertEquals("https://cdn.test/thumbs.webp", sprites[0].url)
    }

    @Test
    fun aSubtitleFileProducesNoThumbnails() {
        // Handed to the sprite parser by mistake. No thumbnails is the right
        // answer; a scrubber full of zero-sized images is not.
        assertTrue(parseVttSprite(CHAPTERS).isEmpty())
    }

    @Test
    fun aMalformedRectangleIsSkippedRatherThanGuessed() {
        // Three numbers is not a rectangle, and defaulting the fourth puts a
        // thumbnail somewhere it is not.
        val broken: String = SPRITES.replace("#xywh=0,0,320,178", "#xywh=0,0,320")

        assertEquals(1, parseVttSprite(broken).size)
    }
}
